name: Release

on:
  release:
    types: [published]

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - name: Download VB Compiler Image
        run: |
          Invoke-WebRequest "${{ secrets.COMPILER_IMAGE_URL }}" -OutFile vb_compiler_image.zip
         
      - name: Unzip Image
        run: |
          Expand-Archive -Path "vb_compiler_image.zip" -DestinationPath "vb_compiler_image"
          
      - name: Install + Verify Runtime
        run: |
          $process = Start-Process -FilePath ".\vb_compiler_image\runtime_setup.exe" -ArgumentList "/silent" -Wait -PassThru        
          $exitCode = $process.ExitCode
          if ($exitCode -eq 0 -or $exitCode -eq 3010)
          {
              Write-Host "Installation successful"
          }
          else
          {
              Write-Host "Non zero exit code returned by the installation process: $exitCode"
              exit $exitCode
          }
          
      - name: Install + Verify Compiler
        run: |
          $process = Start-Process -FilePath ".\vb_compiler_image\compiler_setup.exe" -ArgumentList "-S" -Wait -PassThru        
          $exitCode = $process.ExitCode
          if ($exitCode -eq 0 -or $exitCode -eq 3010)
          {
              Write-Host "Installation successful"
          }
          else
          {
              Write-Host "Non zero exit code returned by the installation process: $exitCode"
              exit $exitCode
          }
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: './project'
          
      - name: Register Project Dependencies
        shell: powershell
        run: |
          cd ./project/deps
          .\reg_deps.ps1 "../source/AdioAudioLibrary.vbp"
          
      - name: Prepare Compile
        shell: powershell
        run: |
          cd ./project
          .\prepare_build.ps1
          
      - name: Compile Visual Basic Library
        shell: cmd
        run: |         
          CALL ./project/build.bat
          
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-library
          path: ./project/Build

  test:
    runs-on: windows-latest
    needs: compile
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: './project'
          
      - name: Download VSC Image
        run: |
          Invoke-WebRequest "${{ secrets.VSC_IMAGE_URL }}" -OutFile "vsc22.zip"
          
      - name: Unzip VSC Image
        run: |
          Expand-Archive -Path "vsc22.zip" -DestinationPath "vsc22_image"
          
      - name: Install VSC
        run: |
          $process = Start-Process -FilePath ".\vsc22_image\vsc22.exe" -ArgumentList "/silent" -Wait -PassThru        
          $exitCode = $process.ExitCode
          if ($exitCode -eq 0 -or $exitCode -eq 3010)
          {
              Write-Host "Installation successful"
          }
          else
          {
              Write-Host "Non zero exit code returned by the installation process: $exitCode"
              exit $exitCode
          }
          
      - name: Download deploy artifact
        uses: actions/download-artifact@v4
        with:
          name: compiled-library
          path: './project/build'
          
      - name: Register Project Dependencies
        shell: powershell
        run: |
          cd ./project/deps
          .\reg_deps.ps1 "../source/AdioAudioLibrary.vbp"
          
      - name: Prepare Test
        shell: powershell
        run: |
          cd ./project
          .\prepare_test.ps1
          
      - name: Run Unit Testing Tool
        shell: cmd
        run: |         
          CALL "./project/Tests/AdioLibraryTests.exe"

  release:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: './project'

      - name: Download deploy artifact
        uses: actions/download-artifact@v4
        with:
          name: compiled-library
          path: './project/build'
      
      - name: Build NuGet package
        shell: cmd
        run: |     
          cd ./project
          dotnet nuget pack AdioLibrary.nuspec

      - name: Publish NuGet package
        shell: cmd
        run: |
          cd ./project
          dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
    
